name: recallCE
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - scikit-learn=0.22.1
  - scikit-image
  - scipy=1.4.1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1
  - opencv=4.2.0
  - protobuf=3.12.3
  - tensorboardx=2.0
  - pytorch=1.5.0
  - torchvision=0.6.0
  - pyyaml
  - tqdm
  - pandas
  - wand

